name: fit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.24.0
  crypto: ^3.0.6
  freezed_annotation: ^3.1.0
  uuid: ^4.5.3
  path_provider: ^2.1.5
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.6.0+eol
  sqlite3: ^3.0.0
  json_annotation: ^4.9.0
  google_generative_ai: ^0.4.7
  sqlite_vector: ^0.9.95
  lottie: ^3.3.2
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.3.1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  supabase_flutter: ^2.12.2
  health: ^13.3.1
  model_viewer_plus: ^1.8.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.24.0
  freezed: ^3.2.5
  json_serializable: ^6.9.5
  mockito: ^5.4.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lottie/exercises/
    - assets/lottie/placeholders/
    - assets/3d/
