// Mocks generated by Mockito 5.4.6 from annotations
// in fit/test/features/ontology/domain/flywheel_sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:fit/features/ontology/data/database/database.dart' as _i2;
import 'package:fit/features/ontology/data/database/exercise_dao.dart' as _i5;
import 'package:fit/features/ontology/domain/enums/ontology_enums.dart' as _i9;
import 'package:fit/features/ontology/domain/models/ontology_models.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_1 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_2 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_3 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_4 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_5 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$EquipmentTable_6 extends _i1.SmartFake
    implements _i2.$EquipmentTable {
  _Fake$EquipmentTable_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$MuscleRegionsTable_7 extends _i1.SmartFake
    implements _i2.$MuscleRegionsTable {
  _Fake$MuscleRegionsTable_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ExercisesTable_8 extends _i1.SmartFake
    implements _i2.$ExercisesTable {
  _Fake$ExercisesTable_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ExerciseMusclesTable_9 extends _i1.SmartFake
    implements _i2.$ExerciseMusclesTable {
  _Fake$ExerciseMusclesTable_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$ExerciseAliasesTable_10 extends _i1.SmartFake
    implements _i2.$ExerciseAliasesTable {
  _Fake$ExerciseAliasesTable_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SubstitutionFeedbackTable_11 extends _i1.SmartFake
    implements _i2.$SubstitutionFeedbackTable {
  _Fake$SubstitutionFeedbackTable_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$SyncQueueTable_12 extends _i1.SmartFake
    implements _i2.$SyncQueueTable {
  _Fake$SyncQueueTable_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UserPreferencesTable_13 extends _i1.SmartFake
    implements _i2.$UserPreferencesTable {
  _Fake$UserPreferencesTable_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UserMuscleConstraintsTable_14 extends _i1.SmartFake
    implements _i2.$UserMuscleConstraintsTable {
  _Fake$UserMuscleConstraintsTable_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeExerciseDaoManager_15 extends _i1.SmartFake
    implements _i5.ExerciseDaoManager {
  _FakeExerciseDaoManager_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExercise_16 extends _i1.SmartFake implements _i6.Exercise {
  _FakeExercise_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_17<T1> extends _i1.SmartFake implements _i7.Future<T1> {
  _FakeFuture_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_18<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_19<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_20<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake
    implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_21<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_22<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_23<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_24<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_25 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExerciseDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseDao extends _i1.Mock implements _i5.ExerciseDao {
  @override
  _i2.AppDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeAppDatabase_0(
              this,
              Invocation.getter(#attachedDatabase),
            ),
            returnValueForMissingStub: _FakeAppDatabase_0(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i2.AppDatabase);

  @override
  _i3.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_1(
              this,
              Invocation.getter(#connection),
            ),
            returnValueForMissingStub: _FakeDatabaseConnection_1(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i3.DatabaseConnection);

  @override
  _i3.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_2(
              this,
              Invocation.getter(#options),
            ),
            returnValueForMissingStub: _FakeDriftDatabaseOptions_2(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i3.DriftDatabaseOptions);

  @override
  _i3.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i8.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
            returnValueForMissingStub: _i8.dummyValue<_i3.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_3(
              this,
              Invocation.getter(#executor),
            ),
            returnValueForMissingStub: _FakeQueryExecutor_3(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_4(
              this,
              Invocation.getter(#streamQueries),
            ),
            returnValueForMissingStub: _FakeStreamQueryStore_4(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_5(
              this,
              Invocation.getter(#resolvedEngine),
            ),
            returnValueForMissingStub: _FakeDatabaseConnectionUser_5(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i3.DatabaseConnectionUser);

  @override
  _i2.$EquipmentTable get equipment =>
      (super.noSuchMethod(
            Invocation.getter(#equipment),
            returnValue: _Fake$EquipmentTable_6(
              this,
              Invocation.getter(#equipment),
            ),
            returnValueForMissingStub: _Fake$EquipmentTable_6(
              this,
              Invocation.getter(#equipment),
            ),
          )
          as _i2.$EquipmentTable);

  @override
  _i2.$MuscleRegionsTable get muscleRegions =>
      (super.noSuchMethod(
            Invocation.getter(#muscleRegions),
            returnValue: _Fake$MuscleRegionsTable_7(
              this,
              Invocation.getter(#muscleRegions),
            ),
            returnValueForMissingStub: _Fake$MuscleRegionsTable_7(
              this,
              Invocation.getter(#muscleRegions),
            ),
          )
          as _i2.$MuscleRegionsTable);

  @override
  _i2.$ExercisesTable get exercises =>
      (super.noSuchMethod(
            Invocation.getter(#exercises),
            returnValue: _Fake$ExercisesTable_8(
              this,
              Invocation.getter(#exercises),
            ),
            returnValueForMissingStub: _Fake$ExercisesTable_8(
              this,
              Invocation.getter(#exercises),
            ),
          )
          as _i2.$ExercisesTable);

  @override
  _i2.$ExerciseMusclesTable get exerciseMuscles =>
      (super.noSuchMethod(
            Invocation.getter(#exerciseMuscles),
            returnValue: _Fake$ExerciseMusclesTable_9(
              this,
              Invocation.getter(#exerciseMuscles),
            ),
            returnValueForMissingStub: _Fake$ExerciseMusclesTable_9(
              this,
              Invocation.getter(#exerciseMuscles),
            ),
          )
          as _i2.$ExerciseMusclesTable);

  @override
  _i2.$ExerciseAliasesTable get exerciseAliases =>
      (super.noSuchMethod(
            Invocation.getter(#exerciseAliases),
            returnValue: _Fake$ExerciseAliasesTable_10(
              this,
              Invocation.getter(#exerciseAliases),
            ),
            returnValueForMissingStub: _Fake$ExerciseAliasesTable_10(
              this,
              Invocation.getter(#exerciseAliases),
            ),
          )
          as _i2.$ExerciseAliasesTable);

  @override
  _i2.$SubstitutionFeedbackTable get substitutionFeedback =>
      (super.noSuchMethod(
            Invocation.getter(#substitutionFeedback),
            returnValue: _Fake$SubstitutionFeedbackTable_11(
              this,
              Invocation.getter(#substitutionFeedback),
            ),
            returnValueForMissingStub: _Fake$SubstitutionFeedbackTable_11(
              this,
              Invocation.getter(#substitutionFeedback),
            ),
          )
          as _i2.$SubstitutionFeedbackTable);

  @override
  _i2.$SyncQueueTable get syncQueue =>
      (super.noSuchMethod(
            Invocation.getter(#syncQueue),
            returnValue: _Fake$SyncQueueTable_12(
              this,
              Invocation.getter(#syncQueue),
            ),
            returnValueForMissingStub: _Fake$SyncQueueTable_12(
              this,
              Invocation.getter(#syncQueue),
            ),
          )
          as _i2.$SyncQueueTable);

  @override
  _i2.$UserPreferencesTable get userPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#userPreferences),
            returnValue: _Fake$UserPreferencesTable_13(
              this,
              Invocation.getter(#userPreferences),
            ),
            returnValueForMissingStub: _Fake$UserPreferencesTable_13(
              this,
              Invocation.getter(#userPreferences),
            ),
          )
          as _i2.$UserPreferencesTable);

  @override
  _i2.$UserMuscleConstraintsTable get userMuscleConstraints =>
      (super.noSuchMethod(
            Invocation.getter(#userMuscleConstraints),
            returnValue: _Fake$UserMuscleConstraintsTable_14(
              this,
              Invocation.getter(#userMuscleConstraints),
            ),
            returnValueForMissingStub: _Fake$UserMuscleConstraintsTable_14(
              this,
              Invocation.getter(#userMuscleConstraints),
            ),
          )
          as _i2.$UserMuscleConstraintsTable);

  @override
  _i5.ExerciseDaoManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _FakeExerciseDaoManager_15(
              this,
              Invocation.getter(#managers),
            ),
            returnValueForMissingStub: _FakeExerciseDaoManager_15(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i5.ExerciseDaoManager);

  @override
  _i7.Future<_i6.Exercise?> getExerciseById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseById, [id]),
            returnValue: _i7.Future<_i6.Exercise?>.value(),
            returnValueForMissingStub: _i7.Future<_i6.Exercise?>.value(),
          )
          as _i7.Future<_i6.Exercise?>);

  @override
  _i7.Future<List<_i6.Exercise>> getAllExercises({
    int? tier,
    String? muscleGroup,
    String? equipmentId,
    String? movementPattern,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllExercises, [], {
              #tier: tier,
              #muscleGroup: muscleGroup,
              #equipmentId: equipmentId,
              #movementPattern: movementPattern,
            }),
            returnValue: _i7.Future<List<_i6.Exercise>>.value(<_i6.Exercise>[]),
            returnValueForMissingStub: _i7.Future<List<_i6.Exercise>>.value(
              <_i6.Exercise>[],
            ),
          )
          as _i7.Future<List<_i6.Exercise>>);

  @override
  _i7.Future<List<_i6.Exercise>> searchByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchByName, [query]),
            returnValue: _i7.Future<List<_i6.Exercise>>.value(<_i6.Exercise>[]),
            returnValueForMissingStub: _i7.Future<List<_i6.Exercise>>.value(
              <_i6.Exercise>[],
            ),
          )
          as _i7.Future<List<_i6.Exercise>>);

  @override
  _i7.Future<List<_i6.MuscleRegion>> getAllMuscleRegions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMuscleRegions, []),
            returnValue: _i7.Future<List<_i6.MuscleRegion>>.value(
              <_i6.MuscleRegion>[],
            ),
            returnValueForMissingStub: _i7.Future<List<_i6.MuscleRegion>>.value(
              <_i6.MuscleRegion>[],
            ),
          )
          as _i7.Future<List<_i6.MuscleRegion>>);

  @override
  _i7.Future<Map<String, List<_i6.MuscleRegion>>> getMuscleRegionsByGroup() =>
      (super.noSuchMethod(
            Invocation.method(#getMuscleRegionsByGroup, []),
            returnValue: _i7.Future<Map<String, List<_i6.MuscleRegion>>>.value(
              <String, List<_i6.MuscleRegion>>{},
            ),
            returnValueForMissingStub:
                _i7.Future<Map<String, List<_i6.MuscleRegion>>>.value(
                  <String, List<_i6.MuscleRegion>>{},
                ),
          )
          as _i7.Future<Map<String, List<_i6.MuscleRegion>>>);

  @override
  _i7.Future<List<_i6.EquipmentModel>> getAllEquipment() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEquipment, []),
            returnValue: _i7.Future<List<_i6.EquipmentModel>>.value(
              <_i6.EquipmentModel>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i6.EquipmentModel>>.value(
                  <_i6.EquipmentModel>[],
                ),
          )
          as _i7.Future<List<_i6.EquipmentModel>>);

  @override
  _i7.Future<void> insertExercise({
    required _i2.ExercisesCompanion? exercise,
    required List<_i2.ExerciseMusclesCompanion>? muscles,
    required List<_i2.ExerciseAliasesCompanion>? aliases,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertExercise, [], {
              #exercise: exercise,
              #muscles: muscles,
              #aliases: aliases,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateExercise(
    String? exerciseId,
    _i2.ExercisesCompanion? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateExercise, [exerciseId, updates]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteExercise(String? exerciseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExercise, [exerciseId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> insertAlias(_i2.ExerciseAliasesCompanion? alias) =>
      (super.noSuchMethod(
            Invocation.method(#insertAlias, [alias]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> rejectSubstitution({
    required String? id,
    required String? userId,
    required String? sourceExerciseId,
    required String? rejectedExerciseId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rejectSubstitution, [], {
              #id: id,
              #userId: userId,
              #sourceExerciseId: sourceExerciseId,
              #rejectedExerciseId: rejectedExerciseId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<String>> getRejectedExerciseIds({
    required String? userId,
    required String? sourceExerciseId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRejectedExerciseIds, [], {
              #userId: userId,
              #sourceExerciseId: sourceExerciseId,
            }),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i7.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<void> enqueueSyncAction({
    required String? id,
    required _i9.SyncAction? action,
    required String? payload,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueueSyncAction, [], {
              #id: id,
              #action: action,
              #payload: payload,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i2.SyncQueueData>> getPendingSyncTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingSyncTasks, []),
            returnValue: _i7.Future<List<_i2.SyncQueueData>>.value(
              <_i2.SyncQueueData>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i2.SyncQueueData>>.value(
                  <_i2.SyncQueueData>[],
                ),
          )
          as _i7.Future<List<_i2.SyncQueueData>>);

  @override
  _i7.Future<void> updateSyncStatus(
    String? id,
    _i9.SyncStatus? status, {
    String? error,
    DateTime? processedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateSyncStatus,
              [id, status],
              {#error: error, #processedAt: processedAt},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i6.MuscleConstraint>> getActiveMuscleConstraints(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMuscleConstraints, [userId]),
            returnValue: _i7.Future<List<_i6.MuscleConstraint>>.value(
              <_i6.MuscleConstraint>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i6.MuscleConstraint>>.value(
                  <_i6.MuscleConstraint>[],
                ),
          )
          as _i7.Future<List<_i6.MuscleConstraint>>);

  @override
  _i7.Stream<List<_i6.MuscleConstraint>> watchActiveMuscleConstraints(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveMuscleConstraints, [userId]),
            returnValue: _i7.Stream<List<_i6.MuscleConstraint>>.empty(),
            returnValueForMissingStub:
                _i7.Stream<List<_i6.MuscleConstraint>>.empty(),
          )
          as _i7.Stream<List<_i6.MuscleConstraint>>);

  @override
  _i7.Future<void> saveMuscleConstraint(
    _i2.UserMuscleConstraintsCompanion? entry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveMuscleConstraint, [entry]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeMuscleConstraint(String? userId, String? muscleId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMuscleConstraint, [userId, muscleId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i6.ExercisePreference>> getExercisePreferences(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExercisePreferences, [userId]),
            returnValue: _i7.Future<List<_i6.ExercisePreference>>.value(
              <_i6.ExercisePreference>[],
            ),
            returnValueForMissingStub:
                _i7.Future<List<_i6.ExercisePreference>>.value(
                  <_i6.ExercisePreference>[],
                ),
          )
          as _i7.Future<List<_i6.ExercisePreference>>);

  @override
  _i7.Future<void> saveExercisePreference(
    _i2.UserPreferencesCompanion? entry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveExercisePreference, [entry]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i6.Exercise> hydrateExercise(_i2.ExerciseData? row) =>
      (super.noSuchMethod(
            Invocation.method(#hydrateExercise, [row]),
            returnValue: _i7.Future<_i6.Exercise>.value(
              _FakeExercise_16(
                this,
                Invocation.method(#hydrateExercise, [row]),
              ),
            ),
            returnValueForMissingStub: _i7.Future<_i6.Exercise>.value(
              _FakeExercise_16(
                this,
                Invocation.method(#hydrateExercise, [row]),
              ),
            ),
          )
          as _i7.Future<_i6.Exercise>);

  @override
  _i7.Stream<T> createStream<T extends Object>(
    _i4.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i7.Stream<T>.empty(),
            returnValueForMissingStub: _i7.Stream<T>.empty(),
          )
          as _i7.Stream<T>);

  @override
  T alias<T, D>(_i3.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i8.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
            returnValueForMissingStub: _i8.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Stream<Set<_i3.TableUpdate>> tableUpdates([
    _i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i7.Stream<Set<_i3.TableUpdate>>.empty(),
            returnValueForMissingStub: _i7.Stream<Set<_i3.TableUpdate>>.empty(),
          )
          as _i7.Stream<Set<_i3.TableUpdate>>);

  @override
  _i7.Future<T> doWhenOpened<T>(
    _i7.FutureOr<T> Function(_i3.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(this, Invocation.method(#doWhenOpened, [fn])),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i7.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_18<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
            returnValueForMissingStub: _FakeInsertStatement_18<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
    _i3.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_19<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
            returnValueForMissingStub: _FakeUpdateStatement_19<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_20<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeSimpleSelectStatement_20<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_21<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeJoinedSelectStatement_21<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
    Iterable<_i3.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_22<_i3.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
            returnValueForMissingStub:
                _FakeBaseSelectStatement_22<_i3.TypedResult>(
                  this,
                  Invocation.method(#selectExpressions, [columns]),
                ),
          )
          as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
    _i3.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_23<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
            returnValueForMissingStub: _FakeDeleteStatement_23<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i3.DeleteStatement<T, D>);

  @override
  _i7.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i7.Future<int>.value(0),
            returnValueForMissingStub: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i7.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
            returnValueForMissingStub: _i7.Future<List<_i3.QueryRow>>.value(
              <_i3.QueryRow>[],
            ),
          )
          as _i7.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_24<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_24<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_24<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_24<_i3.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i3.Selectable<_i3.QueryRow>);

  @override
  _i7.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<T> transaction<T>(
    _i7.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i7.Future<T>);

  @override
  _i7.Future<T> exclusively<T>(_i7.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i7.Future<T>);

  @override
  _i7.Future<void> batch(_i7.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<T> runWithInterceptor<T>(
    _i7.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i7.Future<T>.value(v),
                ) ??
                _FakeFuture_17<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i7.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_25(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_25(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_25(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_25(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i3.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
